dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -vv
stages:
  - test
  - deploy
jobs:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"
  include:
    - stage: deploy
      if: (NOT type IN (pull_request)) AND (branch = master)
      script: cd docs && make html && touch _build/html/.nojekyll && cd ../
      before_deploy:
        - git config --local user.name "$GITHUB_USERNAME"
        - git config --local user.email "$GITHUB_EMAIL"
        - export TRAVIS_TAG=v$(grep -Po '[0-9]+(\.[0-9]+)*' byte_api/__init__.py)
      deploy:
        - provider: pages
          skip_cleanup: true
          token: $GITHUB_TOKEN
          keep_history: true
          local_dir: docs/_build/html
        - provider: pypi
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          server: https://upload.pypi.org/legacy/
        - provider: releases
          api_key: $GITHUB_TOKEN
          skip_cleanup: true
          target_commitish: $TRAVIS_COMMIT
          tag_name: $TRAVIS_TAG
branches:
  only:
  - master
  - develop
  - /^release-.*$/
